### ISSUE TITLE
Artwork not showing up in iTunes

### ISSUE THREAD

**Issue by Retro-R** [KristoforMaynard/music-tag#14]
I'm using a mac, and i've saved my artwork from url. It shows up fine in like the finder folder, as in it shows the artwork in the preview but when i open it in iTunes the artwork doesn't display. idk if this is something wrong w iTunes or something but i was just curious if anyone else had this issue and how they solved it.

**Comment by KristoforMaynard** [comment]
Not enough information to understand the issue.

**Comment by hammady** [comment]
I have the same question. I did the following:
```python
tags = music_tag.load_file(media_path)
with open('artwork.jpg', 'rb') as img:
  tags["artwork"] = img.read()
tags.save()
```
Here is OneDrive link to the file: https://1drv.ms/u/s!Aq1PMiDnHe9tk5Ygn_JVNQ3vMPjNjQ?e=3yBrB2

macOS Finder:

<img width="568" alt="image" src="https://github.com/KristoforMaynard/music-tag/assets/855847/d868f6ca-037f-481d-82d3-039903ba7d97">

Mp3Tag (macOS app):

<img width="667" alt="image" src="https://github.com/KristoforMaynard/music-tag/assets/855847/169d8543-8b4d-4fa6-8daa-15c420dcf754">

iTunes Library (Apple Music):

<img width="590" alt="image" src="https://github.com/KristoforMaynard/music-tag/assets/855847/964eb87e-591f-4e46-84f9-997249fe8701">

Clearly there is a compatibility issue. I have 40GB of media files that I want to sync to my Apple devices, all of them missing the artwork which is important. Any help is appreciated!

**Comment by hammady** [comment]
Finally a solution:
Just make sure Pillow is installed before setting the artwork tag! I discovered this by chance when I was trying to set the thumbnail and I knew from the docs that thumbnails require Pillow. While tagging around 1200 files, 3 of them crashed with the below error when setting the artwork itself, before the thumbnail, so I knew something is being done differently!
Now they all show in iTunes.

The error:
```
  File ".venv/lib/python3.11/site-packages/music_tag/file.py", line 187, in __init__
    depth = mode2depth[img.mode]
            ~~~~~~~~~~^^^^^^^^^^
KeyError: 'LA'
```

Apparently some JPEG files have an unsupported mode, but that's another issue.

**Comment by hammady** [comment]
Created issue #44.
