### ISSUE TITLE
mpv can't display Album art, (But mpv works if ffmpeg is used)

### ISSUE THREAD

**Issue by Liupold** [KristoforMaynard/music-tag#15]
Error: (On the provided sample).
This is the case only with mp3, (opus, ogg, flac works) 
```
[ffmpeg] Unknown attached picture mimetype: , skipping.
```
OS: `Arch Linux`
MPV: `mpv 0.33.1-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 project`

**Comment by Liupold** [comment]
Probably  due to:
https://github.com/FFmpeg/FFmpeg/blob/29b244ffc15abe2c24d2145f63048e8b3bdaa303/libavformat/id3v2.c#L637

**Comment by Liupold** [comment]
As this is solved by the latest commit, once the package  is updated in `pypi`, Feel free to close this issue. Thanks for the quickfix.

**Comment by KristoforMaynard** [comment]
I got to this before seeing your PR. The GitHub workflow looks cool, but I didn't look deep enough to see what it actually does. Does it feed CI somehow? If you take out commit cb49039, I'm happy to merge the PR.
