### ISSUE TITLE
music_tag.load_file() can alter path-name and lead to exception

### ISSUE THREAD

**Issue by orgua** [KristoforMaynard/music-tag#2]
input file example: "10. Time = $$$.opus"

music_tag.load_file() has os.path.expand###() in the first line:
   filename = os.path.expanduser(os.path.expandvars(filename))

unfortunately os.path.expandvars() changes the file-name to "10. Time = $$.opus". This one clearly doesn't match and causes the exception. 

i added an additional argument "path_expand:bool=True" to the function (in my fork), so the function behaves as before, but can be changed if you already work with absolute paths / os.path-Lib. 

Another solution would be to check if the file exists or python can see it and don't expand as a result.

**Comment by KristoforMaynard** [comment]
I can't replicate this issue - maybe there's something missing in my environment. In any event, I prefer the latter solution. There's no need to bother the user with an option on account of an edge case.

**Comment by orgua** [comment]
just for reference for the archive - i run windows 10 on ntfs with python 3.7. 
Coming from c++ i had to smile while looking at your solution. it should work, but even in bestcase it has three additional exists() calls. would have nested it - but python will propably optimize it on its own. thanks for the quick fix!
