### ISSUE TITLE
is a command line interface within scope?

### ISSUE THREAD

**Issue by wbob** [KristoforMaynard/music-tag#3]
I looked around for audio file cli tagging utils that wrap mutagen to allow explicit naming via cli. I found small [snippets](https://gist.github.com/jangler/3956997) and complete library management [suites](http://beets.io/), but no yet a straightforward mutagen based util.

You explain in https://github.com/KristoforMaynard/music-tag/issues/1#issuecomment-629506904 the initial scope of your lib to be a *opinionated* tag cleaner/sanitizer. Do you see a cli interface to set tags explicitly within the scope of your library or is the opinionated aspect a hinderance and/or you'd rather see music-tag as a dependency of a cli wrapper?

**Comment by KristoforMaynard** [comment]
I think a cli would be a great addition to this lib. I'm too busy to make one but would certainly work with someone if they want to write the code.

**Comment by kkew3** [comment]
Have you tried [exiftool](https://exiftool.org)? It's a handy command line tool to edit tags. And [Ex Falso](https://quodlibet.readthedocs.io/en/latest/index.html) is a GUI tool to edit tags.

**Comment by KristoforMaynard** [comment]
First stab at a CLI is added in version 0.4.0. Usage can be found using:

`python -m music_tag --help`
