### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by romanoh** [KristoforMaynard/music-tag#7]
Is it possible to add custom tags like SERIES?
Is m4b supported? (i think its the almost the same as m4a)
i was thinking about audiobooks.

**Comment by KristoforMaynard** [comment]
I'm not sure what you mean by adding custom tags. You can always use mutagen directly for this sort of thing. Also, audiobooks are out of scope for this library. The idea behind this library is to make it easy to edit a standard set of music-specific tags without having to research how format X stores information Y.
