### ISSUE TITLE
"can't sync to MPEG frame" error with OPUS format

### ISSUE THREAD

**Issue by naftali100** [KristoforMaynard/music-tag#8]
i get this error when i try to open [this](https://mega.nz/file/VMRwlR6L#_m8jdHMAv1wUXm-Gv7i1ImNa2XxmyHrdbNd7sJP-6wc) file

**Comment by KristoforMaynard** [comment]
This error comes from inside mutagen. Without looking at it, I'd guess the file is corrupt, or, less likely, mutagen has a bug.
