### ISSUE TITLE
M4a artist being empty despite fact value is not empty

### ISSUE THREAD

**Issue by danthp4** [KristoforMaynard/music-tag#9]
Hi,

    def get_details(path):
        audiofile = music_tag.load_file(path)
        title = audiofile['title']
        artist = audiofile['artist']
        print(artist.values)
        if str(artist) == "":
            artist = str(audiofile['albumartist']) + " [Album Artist]"
        return title, artist
This returns an empty value for the artist section despite the fact itunes definitely has a value there. Happens for all M4a files not sure why. But album artist works fine.

**Comment by KristoforMaynard** [comment]
I can't replicate this issue. Could you provide an example of how to prepare a file like the ones that are giving you trouble?
